
package Proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://ServerJWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionToDH", targetNamespace = "http://ServerJWS/", className = "Proxy.ConversionToDH")
    @ResponseWrapper(localName = "conversionToDHResponse", targetNamespace = "http://ServerJWS/", className = "Proxy.ConversionToDHResponse")
    @Action(input = "http://ServerJWS/BankService/conversionToDHRequest", output = "http://ServerJWS/BankService/conversionToDHResponse")
    public double conversionToDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns Proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createNewCompte", targetNamespace = "http://ServerJWS/", className = "Proxy.CreateNewCompte")
    @ResponseWrapper(localName = "createNewCompteResponse", targetNamespace = "http://ServerJWS/", className = "Proxy.CreateNewCompteResponse")
    @Action(input = "http://ServerJWS/BankService/createNewCompteRequest", output = "http://ServerJWS/BankService/createNewCompteResponse")
    public Compte createNewCompte();

}
